// Avatar SDK runtime version file
// @generated on 04/02/2025, at 09:47:07 UTC from AndroidManifest.xml
//
// DO NOT MODIFY THIS FILE BY HAND, IT IS AUTOGENERATED

using System;
using System.Runtime.InteropServices;

namespace Oculus.Avatar2
{

  public static partial class AvatarSDKVersion
  {
    public const UInt32 AVATAR2_RELEASE_VERSION = 35;
    public const UInt32 AVATAR2_HOTFIX_VERSION = 1;
    public const UInt32 AVATAR2_EXPERIMENTATION_VERSION = 0;
    public const UInt32 AVATAR2_BETA_VERSION = 81;
    public const UInt32 AVATAR2_ALPHA_VERSION = 106;

    static public FBVersionNumber CurrentVersion()
    {
        FBVersionNumber versionNumber;
        versionNumber.releaseVersion = AVATAR2_RELEASE_VERSION;
        versionNumber.hotfixVersion = AVATAR2_HOTFIX_VERSION;
        versionNumber.experimentationVersion = AVATAR2_EXPERIMENTATION_VERSION;
        versionNumber.betaVersion = AVATAR2_BETA_VERSION;
        versionNumber.alphaVersion = AVATAR2_ALPHA_VERSION;

        return versionNumber;
    }
  }
}
